// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtZRvxQSidgBcjJaORkTYoppRUu5BJElE',
    appId: '1:455331920012:web:2783172acf9dc7fa1123a9',
    messagingSenderId: '455331920012',
    projectId: 'somba-app-2026',
    authDomain: 'somba-app-2026.firebaseapp.com',
    storageBucket: 'somba-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvTDpcuyB3rXpmeVRrwh_OPrYGQQFJUyk',
    appId: '1:455331920012:android:4112a05b01f0f12b1123a9',
    messagingSenderId: '455331920012',
    projectId: 'somba-app-2026',
    storageBucket: 'somba-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqPtqmvM0SCU7-JtoJXR4Uq-mAbr5zZhk',
    appId: '1:455331920012:ios:7266814adc62d7511123a9',
    messagingSenderId: '455331920012',
    projectId: 'somba-app-2026',
    storageBucket: 'somba-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.somba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqPtqmvM0SCU7-JtoJXR4Uq-mAbr5zZhk',
    appId: '1:455331920012:ios:7266814adc62d7511123a9',
    messagingSenderId: '455331920012',
    projectId: 'somba-app-2026',
    storageBucket: 'somba-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.somba',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtZRvxQSidgBcjJaORkTYoppRUu5BJElE',
    appId: '1:455331920012:web:d0fbd6fbc57b827e1123a9',
    messagingSenderId: '455331920012',
    projectId: 'somba-app-2026',
    authDomain: 'somba-app-2026.firebaseapp.com',
    storageBucket: 'somba-app-2026.firebasestorage.app',
  );
}
